stages:
    - build
    - deploy

build_app:
    stage: build
    script:
        - export GO15VENDOREXPERIMENT=1
        - mkdir -p /go/src/umputun.com
        - cd /go/src/umputun.com/ureadability
        - go get -v
        - go get -t ./...
        - go test  -v -short -cover ./...
        - GO15VENDOREXPERIMENT=1 go build -o /srv/ureadability
    artifacts:
        paths:
            - /srv/
    tags:
        - go
