stages:
    - build
    - deploy

build_app:
    stage: build
    script:
        - mkdir -p /go/src/ukeeper.com/ureadability
        - ln -s /builds/ureadability/app /go/src/ukeeper.com/ureadability/app
        - cd /go/src/ukeeper.com/ureadability/app
        - go get -v
        - go get -t ./...
        - go test  -v -short -cover ./...
        # go build -ldflags "-X main.gitRevision=$(git --no-pager log -1 --format=%h/%aI)" -o /srv/ureadability
        - go build -o /srv/ureadability
    artifacts:
        paths:
            - /srv/
    tags:
        - go
