version: '2'
services:
  ureadability:
    build: .
    image: umputun/ureadability:latest
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    hostname: ureadability
    restart: always
    container_name: ureadability

    links:
      - mongo

    environment:
      - MONGO=mongo
      - MONGO_PASSWD=Squid3kIc6Dew4ad8Ci5
      - MONGO_DELAY=10
      - CREDS=test:l4!AzQVW1dSN0T^7IJGn&Kr!kwRSF2P1

    ports:
      - "8080:8080"

  mongo:
    image: mongo:4.4
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    hostname: mongo
    restart: always
    container_name: ureadability-mongo

    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Squid3kIc6Dew4ad8Ci5
    volumes:
      - /tmp/mongodb:/data/db
