services:
  ureadability:
    build: .
    image: ghcr.io/ukeeper/ukeeper-readability:latest
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    hostname: ureadability
    restart: always
    container_name: ureadability

    links:
      - mongo

    environment:
      - MONGO_URI=mongodb://root:Squid3kIc6Dew4ad8Ci5@mongo:27017
      - MONGO_DELAY=10s
      - CREDS=admin:jpm6AQH!kbx2tvk!fqc
      #- OPENAI_KEY=insert_key_here

    ports:
      - "8080:8080"

  mongo:
    image: mongo:5.0
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    hostname: mongo
    restart: always
    container_name: ureadability-mongo

    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Squid3kIc6Dew4ad8Ci5
    volumes:
      - /tmp/mongodb:/data/db

# uncomment the lines below to have mongodb ready for tests,
# then start them by running
# `ENABLE_MONGO_TESTS=true go test ./...`
#  mongo-tests:
#    image: mongo:5.0
#    logging:
#      driver: json-file
#      options:
#        max-size: "20m"
#        max-file: "5"
#    hostname: mongo-tests
#    restart: always
#    container_name: ureadability-mongo-tests
#    ports:
#      - "27017:27017"
#    environment:
#      - MONGO_INITDB_DATABASE=admin
