version: '2'
services:
  ureadability:
    build: .
    image: umputun/ureadability:latest
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    hostname: ureadability
    restart: always
    container_name: ureadability

    links:
      - mongo

    environment:
      - MONGO_URI=mongodb://root:Squid3kIc6Dew4ad8Ci5
      - MONGO_DELAY=10s
      - CREDS=test:l4!AzQVW1dSN0T^7IJGn&Kr!kwRSF2P1

    ports:
      - "8080:8080"

  mongo:
    image: mongo:5.0
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    hostname: mongo
    restart: always
    container_name: ureadability-mongo

    # uncomment to make mongo available for tests
    #ports:
    #  - "27017:27017"

    environment:
      - MONGO_INITDB_DATABASE=admin
      # uncomment port and comment the next two lines to have mongodb ready for tests,
      # by running `ENABLE_MONGO_TESTS=true go test ./...`
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Squid3kIc6Dew4ad8Ci5
    volumes:
      - /tmp/mongodb:/data/db
