version: '2'
services:
  ureadability:
    build: .
    image: umputun/ureadability:latest
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    hostname: ureadability
    restart: always
    container_name: ureadability

    links:
      - mongo

    environment:
      - MONGO=mongo
      - MONGO_PASSWD=Squid3kIc6Dew4ad8Ci5
      - MONGO_DELAY=10
      - CREDS=test:$$apr1$q0x6vkft$$s9Lg0jra3GpJ3St0ogepy/

    ports:
      - "8080"

  webapp:
    image: igoradamenko/ureadability-ui
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    hostname: ureadability-ui
    container_name: ureadability-ui

  nginx:
    build: nginx
    restart: always
    hostname: nginx
    container_name: ureadability-nginx
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

    links:
      - server:ureadability
      - webapp
    ports:
      - "8781:80"
    volumes_from:
      - webapp:ro
    environment:
      - NGINX_ADMIN=admin:$$apr1$$pDxqiBaw$$ZarbwfQAjupM3Tg9r/XcR0
      - NGINX_TEST=test:$$apr1$$5s9yoqp3$$NdZSCZr7VTmLEc8Bv/bmq1

  mongo:
    image: mongo:4.4
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    hostname: mongo
    restart: always
    container_name: ureadability-mongo

    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Squid3kIc6Dew4ad8Ci5
    volumes:
      - /tmp/mongodb:/data/db
