// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/ukeeper/ukeeper-readability/datastore"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// RulesMock is a mock implementation of extractor.Rules.
//
//	func TestSomethingThatUsesRules(t *testing.T) {
//
//		// make and configure a mocked extractor.Rules
//		mockedRules := &RulesMock{
//			AllFunc: func(ctx context.Context) []datastore.Rule {
//				panic("mock out the All method")
//			},
//			DisableFunc: func(ctx context.Context, id primitive.ObjectID) error {
//				panic("mock out the Disable method")
//			},
//			GetFunc: func(ctx context.Context, rURL string) (datastore.Rule, bool) {
//				panic("mock out the Get method")
//			},
//			GetByIDFunc: func(ctx context.Context, id primitive.ObjectID) (datastore.Rule, bool) {
//				panic("mock out the GetByID method")
//			},
//			SaveFunc: func(ctx context.Context, rule datastore.Rule) (datastore.Rule, error) {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedRules in code that requires extractor.Rules
//		// and then make assertions.
//
//	}
type RulesMock struct {
	// AllFunc mocks the All method.
	AllFunc func(ctx context.Context) []datastore.Rule

	// DisableFunc mocks the Disable method.
	DisableFunc func(ctx context.Context, id primitive.ObjectID) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, rURL string) (datastore.Rule, bool)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id primitive.ObjectID) (datastore.Rule, bool)

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, rule datastore.Rule) (datastore.Rule, error)

	// calls tracks calls to the methods.
	calls struct {
		// All holds details about calls to the All method.
		All []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Disable holds details about calls to the Disable method.
		Disable []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID primitive.ObjectID
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RURL is the rURL argument value.
			RURL string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID primitive.ObjectID
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Rule is the rule argument value.
			Rule datastore.Rule
		}
	}
	lockAll     sync.RWMutex
	lockDisable sync.RWMutex
	lockGet     sync.RWMutex
	lockGetByID sync.RWMutex
	lockSave    sync.RWMutex
}

// All calls AllFunc.
func (mock *RulesMock) All(ctx context.Context) []datastore.Rule {
	if mock.AllFunc == nil {
		panic("RulesMock.AllFunc: method is nil but Rules.All was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockAll.Lock()
	mock.calls.All = append(mock.calls.All, callInfo)
	mock.lockAll.Unlock()
	return mock.AllFunc(ctx)
}

// AllCalls gets all the calls that were made to All.
// Check the length with:
//
//	len(mockedRules.AllCalls())
func (mock *RulesMock) AllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockAll.RLock()
	calls = mock.calls.All
	mock.lockAll.RUnlock()
	return calls
}

// Disable calls DisableFunc.
func (mock *RulesMock) Disable(ctx context.Context, id primitive.ObjectID) error {
	if mock.DisableFunc == nil {
		panic("RulesMock.DisableFunc: method is nil but Rules.Disable was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  primitive.ObjectID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDisable.Lock()
	mock.calls.Disable = append(mock.calls.Disable, callInfo)
	mock.lockDisable.Unlock()
	return mock.DisableFunc(ctx, id)
}

// DisableCalls gets all the calls that were made to Disable.
// Check the length with:
//
//	len(mockedRules.DisableCalls())
func (mock *RulesMock) DisableCalls() []struct {
	Ctx context.Context
	ID  primitive.ObjectID
} {
	var calls []struct {
		Ctx context.Context
		ID  primitive.ObjectID
	}
	mock.lockDisable.RLock()
	calls = mock.calls.Disable
	mock.lockDisable.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *RulesMock) Get(ctx context.Context, rURL string) (datastore.Rule, bool) {
	if mock.GetFunc == nil {
		panic("RulesMock.GetFunc: method is nil but Rules.Get was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		RURL string
	}{
		Ctx:  ctx,
		RURL: rURL,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, rURL)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRules.GetCalls())
func (mock *RulesMock) GetCalls() []struct {
	Ctx  context.Context
	RURL string
} {
	var calls []struct {
		Ctx  context.Context
		RURL string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *RulesMock) GetByID(ctx context.Context, id primitive.ObjectID) (datastore.Rule, bool) {
	if mock.GetByIDFunc == nil {
		panic("RulesMock.GetByIDFunc: method is nil but Rules.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  primitive.ObjectID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedRules.GetByIDCalls())
func (mock *RulesMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  primitive.ObjectID
} {
	var calls []struct {
		Ctx context.Context
		ID  primitive.ObjectID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *RulesMock) Save(ctx context.Context, rule datastore.Rule) (datastore.Rule, error) {
	if mock.SaveFunc == nil {
		panic("RulesMock.SaveFunc: method is nil but Rules.Save was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Rule datastore.Rule
	}{
		Ctx:  ctx,
		Rule: rule,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, rule)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedRules.SaveCalls())
func (mock *RulesMock) SaveCalls() []struct {
	Ctx  context.Context
	Rule datastore.Rule
} {
	var calls []struct {
		Ctx  context.Context
		Rule datastore.Rule
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
