// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package extractor

import (
	"context"
	"sync"
)

// AIEvaluatorMock is a mock implementation of AIEvaluator.
//
//	func TestSomethingThatUsesAIEvaluator(t *testing.T) {
//
//		// make and configure a mocked AIEvaluator
//		mockedAIEvaluator := &AIEvaluatorMock{
//			EvaluateFunc: func(ctx context.Context, url string, extractedText string, htmlBody string, prevSelector string) (*EvalResult, error) {
//				panic("mock out the Evaluate method")
//			},
//		}
//
//		// use mockedAIEvaluator in code that requires AIEvaluator
//		// and then make assertions.
//
//	}
type AIEvaluatorMock struct {
	// EvaluateFunc mocks the Evaluate method.
	EvaluateFunc func(ctx context.Context, url string, extractedText string, htmlBody string, prevSelector string) (*EvalResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Evaluate holds details about calls to the Evaluate method.
		Evaluate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// URL is the url argument value.
			URL string
			// ExtractedText is the extractedText argument value.
			ExtractedText string
			// HtmlBody is the htmlBody argument value.
			HtmlBody string
			// PrevSelector is the prevSelector argument value.
			PrevSelector string
		}
	}
	lockEvaluate sync.RWMutex
}

// Evaluate calls EvaluateFunc.
func (mock *AIEvaluatorMock) Evaluate(ctx context.Context, url string, extractedText string, htmlBody string, prevSelector string) (*EvalResult, error) {
	if mock.EvaluateFunc == nil {
		panic("AIEvaluatorMock.EvaluateFunc: method is nil but AIEvaluator.Evaluate was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		URL           string
		ExtractedText string
		HtmlBody      string
		PrevSelector  string
	}{
		Ctx:           ctx,
		URL:           url,
		ExtractedText: extractedText,
		HtmlBody:      htmlBody,
		PrevSelector:  prevSelector,
	}
	mock.lockEvaluate.Lock()
	mock.calls.Evaluate = append(mock.calls.Evaluate, callInfo)
	mock.lockEvaluate.Unlock()
	return mock.EvaluateFunc(ctx, url, extractedText, htmlBody, prevSelector)
}

// EvaluateCalls gets all the calls that were made to Evaluate.
// Check the length with:
//
//	len(mockedAIEvaluator.EvaluateCalls())
func (mock *AIEvaluatorMock) EvaluateCalls() []struct {
	Ctx           context.Context
	URL           string
	ExtractedText string
	HtmlBody      string
	PrevSelector  string
} {
	var calls []struct {
		Ctx           context.Context
		URL           string
		ExtractedText string
		HtmlBody      string
		PrevSelector  string
	}
	mock.lockEvaluate.RLock()
	calls = mock.calls.Evaluate
	mock.lockEvaluate.RUnlock()
	return calls
}
