// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package extractor

import (
	"context"
	"sync"
)

// RetrieverMock is a mock implementation of Retriever.
//
//	func TestSomethingThatUsesRetriever(t *testing.T) {
//
//		// make and configure a mocked Retriever
//		mockedRetriever := &RetrieverMock{
//			RetrieveFunc: func(ctx context.Context, url string) (*RetrieveResult, error) {
//				panic("mock out the Retrieve method")
//			},
//		}
//
//		// use mockedRetriever in code that requires Retriever
//		// and then make assertions.
//
//	}
type RetrieverMock struct {
	// RetrieveFunc mocks the Retrieve method.
	RetrieveFunc func(ctx context.Context, url string) (*RetrieveResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Retrieve holds details about calls to the Retrieve method.
		Retrieve []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// URL is the url argument value.
			URL string
		}
	}
	lockRetrieve sync.RWMutex
}

// Retrieve calls RetrieveFunc.
func (mock *RetrieverMock) Retrieve(ctx context.Context, url string) (*RetrieveResult, error) {
	if mock.RetrieveFunc == nil {
		panic("RetrieverMock.RetrieveFunc: method is nil but Retriever.Retrieve was just called")
	}
	callInfo := struct {
		Ctx context.Context
		URL string
	}{
		Ctx: ctx,
		URL: url,
	}
	mock.lockRetrieve.Lock()
	mock.calls.Retrieve = append(mock.calls.Retrieve, callInfo)
	mock.lockRetrieve.Unlock()
	return mock.RetrieveFunc(ctx, url)
}

// RetrieveCalls gets all the calls that were made to Retrieve.
// Check the length with:
//
//	len(mockedRetriever.RetrieveCalls())
func (mock *RetrieverMock) RetrieveCalls() []struct {
	Ctx context.Context
	URL string
} {
	var calls []struct {
		Ctx context.Context
		URL string
	}
	mock.lockRetrieve.RLock()
	calls = mock.calls.Retrieve
	mock.lockRetrieve.RUnlock()
	return calls
}
