name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: checkout
        uses: actions/checkout@v2

      - name: build and test
        working-directory: app
        run: |
          go test -timeout=60s -race -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...
          go build -race
        env:
          TZ: "America/Chicago"

      - name: install golangci-lint and goveralls
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.41.1
          GO111MODULE=off go get -u -v github.com/mattn/goveralls
      - name: run linters
        working-directory: app
        run: $GITHUB_WORKSPACE/golangci-lint run --out-format=github-actions

#      TODO: enable when repo will be enabled in coveralls
#      - name: submit coverage
#        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
#        env:
#          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}